
export enum ExpenseCategory {
  VENUE = 'Local & Cerimônia',
  CATERING = 'Buffet & Bebidas',
  ATTIRE = 'Trajes & Beleza',
  DECOR = 'Decoração & Flores',
  PHOTO_VIDEO = 'Foto & Vídeo',
  MUSIC = 'Música & Iluminação',
  INVITES = 'Convites & Papelaria',
  GIFTS = 'Lembrancinhas',
  OTHER = 'Outros',
  HONEYMOON = 'Lua de Mel' // Added category
}

export enum ExpenseStatus {
  PENDING = 'Pendente',
  DEPOSIT_PAID = 'Sinal Pago',
  PAID = 'Pago Totalmente'
}

export interface Expense {
  id: string;
  name: string;
  category: ExpenseCategory;
  estimatedCost: number;
  paidAmount: number;
  depositRequired: number; // New field for down payment/deposit
  dueDate?: string; // New field for specific payment date (YYYY-MM-DD)
  status: ExpenseStatus;
  notes?: string;
}

export enum GuestSide {
  BRIDE = 'Noiva',
  GROOM = 'Noivo'
}

export interface Guest {
  id: string;
  name: string;
  side: GuestSide;
  confirmed: boolean;
  assignedTableId?: string; // ID da mesa
  assignedSeatIndex?: number; // Índice da cadeira (0 a N)
}

export enum TableShape {
  ROUND = 'Redonda',
  SQUARE = 'Quadrada',
  RECTANGLE = 'Retangular'
}

export interface Table {
  id: string;
  name: string;
  capacity: number;
  shape: TableShape;
}

export type InvitationTheme = 'classic' | 'modern' | 'romantic' | 'rustic';

export interface InvitationData {
  groomName: string;
  brideName: string;
  date: string;
  time: string;
  venue: string;
  address: string;
  message: string;
  theme: InvitationTheme;
}

export interface SavingsPlan {
  currentSavings: number;
  monthlyContribution: number; // How much user can save per month
  targetDate: string; // YYYY-MM-DD
  mode: 'calculate_date' | 'calculate_amount'; // Calculate end date based on contribution OR calculate contribution based on date
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'model';
  text: string;
  isError?: boolean;
}

// Novos tipos para Lista de Presentes Virtual
export interface GiftItem {
  id: string;
  name: string;
  price: number;
  imageUrl: string;
  category?: string;
  totalShares?: number; // Se > 1, é um item de cotas
  soldShares?: number;  // Quantas cotas já foram "compradas" (simulação)
}

// Novos tipos para o Checklist
export interface Task {
  id: string;
  title: string;
  category: string; // 'Burocracia', 'Festa', 'Beleza', etc.
  completed: boolean;
  deadline?: string; // YYYY-MM-DD
  priority: 'low' | 'medium' | 'high';
}

// Novos tipos para o Site dos Noivos
export type WebsiteSectionType = 'hero' | 'text' | 'countdown' | 'gallery' | 'rsvp' | 'location' | 'gifts';

export interface WebsiteSection {
  id: string;
  type: WebsiteSectionType;
  content: {
    title?: string;
    subtitle?: string;
    body?: string;
    imageUrl?: string;
    images?: string[]; // Para galeria
    date?: string;
    buttonText?: string;
    bgColor?: string; // white, slate-50, rose-50, etc.
    alignment?: 'left' | 'center' | 'right';
    bankInfo?: string; // Para presentes/pix
    storeLink?: string;
    showGiftGrid?: boolean; // Se deve mostrar a grade de produtos virtuais
  };
}

export interface WebsiteData {
  title: string;
  globalSettings: {
    primaryColor: string; // hex or tailwind class base
    fontFamily: 'serif' | 'sans' | 'mono' | 'cursive';
  };
  sections: WebsiteSection[];
}

// Novos tipos para Marketplace de Fornecedores (B2B)
export interface Vendor {
  id: string;
  name: string;
  category: ExpenseCategory;
  rating: number;
  reviewsCount: number;
  minPrice: number;
  imageUrl: string;
  isVerified: boolean; // Selo de verificado (Plano B2B Pago)
  isFeatured: boolean; // Destaque na busca (Ads)
  location: string;
}

export interface VendorLead {
  id: string;
  coupleName: string;
  weddingDate: string;
  budget: number;
  message: string;
  status: 'new' | 'read' | 'contacted' | 'booked';
  receivedAt: string;
}

export interface VendorStats {
  profileViews: number;
  clicksToContact: number;
  totalLeads: number;
  conversionRate: number;
  planLevel: 'free' | 'basic' | 'pro';
}

export interface UserSubscription {
  tier: 'free' | 'premium';
  features: string[];
}

// Novo tipo para Mood Board
export interface Inspiration {
  id: string;
  imageUrl: string; // Base64 or URL
  prompt?: string; // If generated by AI
  category: string; // 'Bolo', 'Vestido', etc.
  createdAt: string;
}

// Novo tipo para Busca de Locais (Maps Grounding)
export interface VenueSearchResult {
  name: string;
  address?: string;
  rating?: string;
  user_ratings_total?: string;
  sourceUri?: string; // Google Maps Link
}

// Tipos para Lua de Mel
export interface HoneymoonDestination {
  id: string;
  name: string;
  country: string;
  description: string;
  estimatedCost: number;
  currency: string;
  bestTime: string;
  activities: string[];
  pros: string[];
  cons: string[];
  imageUrl?: string;
}

export interface HoneymoonPlan {
  selectedDestination: HoneymoonDestination | null;
  packingList: { item: string; packed: boolean }[];
  notes: string;
}
